/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Architect_BayesOpt_HOOK */

#ifndef _Included_Architect_BayesOpt_HOOK
#define _Included_Architect_BayesOpt_HOOK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Architect_BayesOpt_HOOK
 * Method:    updateModel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Architect_BayesOpt_1HOOK_updateModel
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Architect_BayesOpt_HOOK
 * Method:    nextParameters
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Architect_BayesOpt_1HOOK_nextParameters
  (JNIEnv *, jclass);

/*
 * Class:     Architect_BayesOpt_HOOK
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Architect_BayesOpt_1HOOK_init
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
