/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_ZMQ_Context */

#ifndef _Included_org_zeromq_ZMQ_Context
#define _Included_org_zeromq_ZMQ_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_ZMQ_Context
 * Method:    construct
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_ZMQ_00024Context_construct
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_zeromq_ZMQ_Context
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zeromq_ZMQ_00024Context_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
